name: Reusable workflow

on:
  workflow_call:
    inputs:
      who-to-greet:
        required: true
        type: string
        default: World
    outputs:
      current-time:
        description: 'The time when greeting.'
        value: ${{ jobs.greet.outputs.current-time }}

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ inputs.who-to-greet }}"
      - id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT
    outputs:
      current-time: ${{ steps.time.outputs.time }}
